theme: jekyll-theme-minimal
title: Harrison Wainwright
logo: https://avatars0.githubusercontent.com/u/26075039?s=400&u=7ed8552cf331ac170e70d0e16d97c70fdfa25e9f&v=4

navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
    - Learn markdown: "http://www.markdowntutorial.com/"
    - GitHub Pages: "https://pages.github.com/"
Author's home: "http://deanattali.com"
